### PR TITLE
Update ansi_loader.cpp

### PR DESCRIPTION
**Pull request by m0qui**
Added nfo file extension to ANSILoader.

### CODE REVIEW

**Comment by kajott** [comment]
I was also thinking about adding more file extensions.
Do you think that `.txt` and `.diz` would make sense too?

**Comment by m0qui** [comment]
Unless you maintain a clean compo directory adding txt and diz might bring unwanted loading of readme.txt and file_id.diz files into the mix ;-)

**Comment by kajott** [comment]
100% correct. For a compo, you need to have a directory with **only** the files you want to show, or have a directory per entry and use [CompoKit](https://github.com/kajott/CompoKit)'s launcher to start the correct one. But I think that's good practice anyway?

OTOH, some `.diz` files, too, look best in Topaz+, so I'm slightly inclined towards adding those, at least. `.txt` is indeed debatable.

**Comment by m0qui** [comment]
Sounds reasonable.

**Pull request merged**
